name: satellogic
channels:
- conda-forge
- defaults
dependencies:
- affine=2.2.0
- appnope=0.1.0
- asn1crypto=0.24.0
- attrs=17.4.0
- blas=1.1
- bleach=2.1.3
- bokeh=0.12.14
- boost=1.66.0
- boost-cpp=1.66.0
- boto3=1.6.7
- botocore=1.9.7
- bzip2=1.0.6
- ca-certificates=2018.1.18
- cairo=1.14.10
- certifi=2018.1.18
- cffi=1.11.5
- chardet=3.0.4
- click=6.7
- click-plugins=1.0.3
- cligj=0.4.0
- cloudpickle=0.5.2
- cryptography=2.1.4
- curl=7.59.0
- cycler=0.10.0
- cytoolz=0.9.0.1
- dask=0.17.2
- dask-core=0.17.2
- dbus=1.10.22
- decorator=4.2.1
- distributed=1.21.4
- docutils=0.14
- entrypoints=0.2.3
- expat=2.2.5
- fiona=1.7.11
- fontconfig=2.12.6
- freetype=2.8.1
- freexl=1.0.5
- gdal=2.2.3
- geojson=2.3.0
- geos=3.6.2
- geotiff=1.4.2
- gettext=0.19.8.1
- giflib=5.1.4
- glib=2.55.0
- hdf4=4.2.13
- hdf5=1.10.1
- heapdict=1.0.0
- html5lib=1.0.1
- icu=58.2
- idna=2.6
- imageio=2.3.0
- ipykernel=4.8.2
- ipython=6.2.1
- ipython_genutils=0.2.0
- ipywidgets=7.1.2
- jedi=0.11.1
- jinja2=2.10
- jmespath=0.9.3
- jpeg=9b
- json-c=0.12.1
- jsonschema=2.6.0
- jupyter=1.0.0
- jupyter_client=5.2.3
- jupyter_console=5.2.0
- jupyter_core=4.4.0
- kealib=1.4.7
- kiwisolver=1.0.1
- krb5=1.14.2
- libdap4=3.18.3
- libffi=3.2.1
- libgdal=2.2.3
- libgfortran=3.0.0
- libiconv=1.15
- libkml=1.3.0
- libnetcdf=4.4.1.1
- libpng=1.6.34
- libpq=9.6.3
- libsodium=1.0.16
- libspatialite=4.3.0a
- libssh2=1.8.0
- libtiff=4.0.9
- libxml2=2.9.8
- locket=0.2.0
- markupsafe=1.0
- matplotlib=2.2.2
- mistune=0.8.3
- msgpack-python=0.5.6
- munch=2.2.0
- nbconvert=5.3.1
- nbformat=4.4.0
- ncurses=5.9
- networkx=2.1
- notebook=5.4.1
- numpy=1.14.2
- olefile=0.45.1
- openblas=0.2.20
- openjpeg=2.3.0
- openssl=1.0.2n
- packaging=17.1
- pandas=0.22.0
- pandoc=2.1.3
- pandocfilters=1.4.1
- parso=0.1.1
- partd=0.3.8
- pcre=8.41
- pexpect=4.4.0
- pickleshare=0.7.4
- pillow=5.0.0
- pip=9.0.3
- pixman=0.34.0
- poppler=0.61.1
- poppler-data=0.4.8
- proj4=4.9.3
- prompt_toolkit=1.0.15
- psutil=5.4.3
- ptyprocess=0.5.2
- pycparser=2.18
- pygments=2.2.0
- pyopenssl=17.5.0
- pyparsing=2.2.0
- pyproj=1.9.5.1
- pyqt=5.6.0
- pysal=1.14.3
- pysocks=1.6.8
- python=3.6.5
- python-dateutil=2.7.0
- pytz=2018.3
- pywavelets=0.5.2
- pyyaml=3.12
- pyzmq=17.0.0
- qt=5.6.2
- qtconsole=4.3.1
- readline=7.0
- requests=2.18.4
- s3transfer=0.1.13
- scikit-image=0.13.1
- scipy=1.0.0
- send2trash=1.5.0
- setuptools=39.0.1
- shapely=1.6.4
- simplegeneric=0.8.1
- sip=4.18
- six=1.11.0
- snuggs=1.4.1
- sortedcontainers=1.5.9
- spectral=0.19
- sqlite=3.20.1
- tblib=1.3.2
- terminado=0.8.1
- testpath=0.3.1
- tk=8.6.7
- toolz=0.9.0
- tornado=5.0.1
- traitlets=4.3.2
- urllib3=1.22
- wcwidth=0.1.7
- webencodings=0.5
- wheel=0.30.0
- widgetsnbextension=3.1.4
- xerces-c=3.2.0
- xz=5.2.3
- yaml=0.1.7
- zeromq=4.2.3
- zict=0.1.3
- zlib=1.2.11
- pip:
  - chroma-py==0.1.0.dev1
  - colour==0.1.5
  - ipython-genutils==0.2.0
  - jupyter-client==5.2.3
  - jupyter-console==5.2.0
  - jupyter-core==4.4.0
  - mapboxgl==0.6.0
  - prompt-toolkit==1.0.15
  - rasterio==1.0a12
